[tool.poetry]
name = "langfuse"
version = "0.0.22"
description = "A client library for accessing langfuse"
authors = ["langfuse <developers@langfuse.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
pytest = "^7.4.0"
python = "^3.8"
httpx = ">=0.15.4,<0.25.0"
attrs = ">=21.3.0"
python-dateutil = "^2.8.0"
pytest-timeout = "^2.1.0"
pydantic = "1.10.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target_version = ['py38', 'py39', 'py310', 'py311']
exclude = '''
(
  /(
    | \.git
    | \.venv
    | \.mypy_cache
  )/
)
'''

[tool.isort]
line_length = 120
profile = "black"


[tool.poetry_bumpversion.file."langfuse/version.py"]